/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Language } from "./components/language-toggle/language-toggle";
export namespace Components {
    interface LanguageToggle {
        "currentLanguage": string;
        "languages": Language[];
    }
}
declare global {
    interface HTMLLanguageToggleElement extends Components.LanguageToggle, HTMLStencilElement {
    }
    var HTMLLanguageToggleElement: {
        prototype: HTMLLanguageToggleElement;
        new (): HTMLLanguageToggleElement;
    };
    interface HTMLElementTagNameMap {
        "language-toggle": HTMLLanguageToggleElement;
    }
}
declare namespace LocalJSX {
    interface LanguageToggle {
        "currentLanguage"?: string;
        "languages"?: Language[];
    }
    interface IntrinsicElements {
        "language-toggle": LanguageToggle;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "language-toggle": LocalJSX.LanguageToggle & JSXBase.HTMLAttributes<HTMLLanguageToggleElement>;
        }
    }
}
