/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Option } from "./components/popover-dropdown/popover-dropdown";
export namespace Components {
    interface PopoverDropdown {
        "currentOption": string;
        "options": Option[];
    }
}
declare global {
    interface HTMLPopoverDropdownElement extends Components.PopoverDropdown, HTMLStencilElement {
    }
    var HTMLPopoverDropdownElement: {
        prototype: HTMLPopoverDropdownElement;
        new (): HTMLPopoverDropdownElement;
    };
    interface HTMLElementTagNameMap {
        "popover-dropdown": HTMLPopoverDropdownElement;
    }
}
declare namespace LocalJSX {
    interface PopoverDropdown {
        "currentOption"?: string;
        "options"?: Option[];
    }
    interface IntrinsicElements {
        "popover-dropdown": PopoverDropdown;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "popover-dropdown": LocalJSX.PopoverDropdown & JSXBase.HTMLAttributes<HTMLPopoverDropdownElement>;
        }
    }
}
